#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  2 13:57:07 2019

@author: davinpc
"""

inventory = {'gold' : 500, 'pouch' : ['flint','twine','gemstone'], 'backpack' : ['xylophone','dagger','bedroll','bread loaf']}
inventory['pocket'] = ['seashell','strange berry','lint']
inventory['backpack'].sort()
inventory['backpack'].remove('dagger')
inventory['gold'] = inventory['gold'] + 50
print(inventory)
