#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  2 15:29:28 2019

@author: davinpc
"""

eren = {
"name": "Eren",
"homework": [90.0,97.0,75.0,92.0], "quizzes": [88.0,40.0,94.0],
"tests": [75.0,90.0]
}
mikasa = {
"name": "Mikasa",
"homework": [100.0, 92.0, 98.0, 100.0], "quizzes": [82.0, 83.0, 91.0],
"tests": [89.0, 97.0]
}
armin = {
"name": "Armin",
"homework": [0.0, 87.0, 75.0, 22.0], "quizzes": [0.0, 75.0, 78.0],
"tests": [100.0, 100.0]
}

students = [eren,mikasa,armin]
for student in students:
    print(student['name'])
    print(student['homework'])
    print(student['quizzes'])
    print(student['tests'])
    
    
def average(numbers):
    total = sum(numbers)
    total = float(total)
    total = total / len(numbers)
    return total

def get_average(student):
    homework = average(student['homework'])
    quizzes = average(student['quizzes'])
    tests = average(student['tests'])
    homework = (homework*10)/100
    quizzes = (quizzes*30)/100
    tests = (tests*60)/100
    totalaverage = homework + quizzes + tests
    return totalaverage
    
def get_letter_grade(score = int):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

print(get_average(armin))
print(get_letter_grade(get_average(armin)))

def get_class_average(students):
    results = []
    for student in students:
        results.append(get_average(student))
        result = average(results)
        return result
    
print(get_class_average(students))
print(get_letter_grade(get_class_average(students)))




