#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  2 11:42:09 2019

@author: davinpc
"""
#2,3,5,7,11,13,17,19
def prime(n):
    if n==1:
        return 2
    count = 1
    num = 3
    while(count <= n):
        if is_prime(num):
            count +=1
            if count == n:
                return num
        num +=2 
        
def is_prime(num):
    factor = 2
    while (factor < num):
        if num%factor == 0:
             return False
        factor +=1
    return True 
        

for n in range(1,10):
    print(prime(n))